#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import click
import os

CONTEXT_SETTINGS = dict(help_option_names=["-h", "--help"])


@click.command(context_settings=CONTEXT_SETTINGS)
@click.argument("folder")
@click.option("--name", "-n", required=False, default=None, help="Patient initials")
def go(folder, name):
    if name is None:
        name = folder

    cmd = f"./rpt_db_set_injection_datetime_from_xls --db {folder}/db.json -n {name} --xls luPSMA_clinical_study.xlsx"
    print()
    print(cmd)
    r = os.system(cmd)

    cmd = f"rpt_db_set_spect_datetime_from_dicom --db {folder}/db.json"
    print()
    print(cmd)
    r = os.system(cmd)

    cmd = f"rpt_db_add_rois --db {folder}/db.json -l oar.json -n {name}"
    print()
    print(cmd)
    r = os.system(cmd)

    cmd = f"rpt_db_spect_calibration --db {folder}/db.json -c 0.176906614"
    print()
    print(cmd)
    r = os.system(cmd)


    cmd = f"rpt_db_rois_activity --db {folder}/db.json"
    print()
    print(cmd)
    r = os.system(cmd)

    cmd = f"rpt_db_info --db {folder}/db.json"
    print()
    print(cmd)
    r = os.system(cmd)


# --------------------------------------------------------------------------
if __name__ == "__main__":
    go()
